### ISSUE TITLE
Thêm file worldset và maplist (và các file liên quan)

### ISSUE THREAD

**Issue by vinh-ttn** [cjgawatama/jx1-tan-lang#1]
Bác TG có thể nào cho mình xin, hoặc thêm vào GitHub các file file maplist và worldset của bác (và các file cần chỉnh sửa khác), nhưng mà là tên khác (ví dụ **maplist_bibao.txt** hoặc **worldset_bibao.txt** (trong s3relay) )

Để AE muốn chơi thì chỉ việc down hết về đổi tên file hiện tại trên server qua tên khác rồi dùng file có sẵn,
khỏi mắc công ngồi sửa theo hướng dẫn hơi bị lâu

Cám ơn bác nhiều.

**Comment by cjgawatama** [comment]
> Bác TG có thể nào cho mình xin, hoặc thêm vào GitHub các file file maplist và worldset của bác (và các file cần chỉnh sửa khác), nhưng mà là tên khác (ví dụ **maplist_bibao.txt** hoặc **worldset_bibao.txt** (trong s3relay) )
> 
> Để AE muốn chơi thì chỉ việc down hết về đổi tên file hiện tại trên server qua tên khác rồi dùng file có sẵn, khỏi mắc công ngồi sửa theo hướng dẫn hơi bị lâu
> 
> Cám ơn bác nhiều.

Được bác, hôm qua mình cũng tải cả những file đó lên nhưng khi test ở một số server do khai báo map từ trước khác nhau dẫn tới lỗi nên mình đổi lại là làm hướng dẫn cho mọi người tự khai báo để tránh lỗi

Đã update những file cần sửa chửa với đuôi " _tanlang" bác có thể tham khảo thêm

**Comment by bombom2000** [comment]
Bác Giang ơi, tứ đại thánh thú là có sẵn trong client game phải ko bác

**Comment by cjgawatama** [comment]
> Bác Giang ơi, tứ đại thánh thú là có sẵn trong client game phải ko bác

Đúng rồi, Tứ thánh thú trong bản 8.0 là được khai báo với có spr sẳn r bác

**Comment by bombom2000** [comment]
Thank bác. Lại có cái để mò mẫm rồi

**Comment by vinh-ttn** [comment]
> Được bác, hôm qua mình cũng tải cả những file đó lên nhưng khi test ở một số server do khai báo map từ trước khác nhau dẫn tới lỗi nên mình đổi lại là làm hướng dẫn cho mọi người tự khai báo để tránh lỗi



cám ơn bác đã add các file (bao gồm npcres :)) ngại nhất là vụ font tiếng tàu này)
